dist: trusty
sudo: required
language: python

python:
  - "2.7"

install:
  - pip install tox cookiecutter
  - pip install -r test-requirements.txt -r requirements.txt

script: 
  - cookiecutter --no-input . 
  - cd webapp
  - flake8
  - nosetests -sv
